import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;

import '../core/config/app_config.dart';

/// Mints a single-use Terra auth token by calling `generateAuthToken` directly.
///
/// ⚠️ **DEV / TESTING ONLY.** In production the token is generated by the
/// Personally backend (which alone holds the secret API key) and handed to the
/// app via the deep link. This client-side path exists so "Connect Apple
/// Health" works when running the app standalone, and is a no-op unless
/// `TERRA_API_KEY` is supplied via `--dart-define`.
class TerraAuthService {
  TerraAuthService({http.Client? client}) : _client = client ?? http.Client();

  final http.Client _client;

  static final Uri _endpoint =
      Uri.parse('https://api.tryterra.co/v2/auth/generateAuthToken');

  /// Returns a fresh token, or `null` if no API key is configured or the call
  /// fails.
  Future<String?> generateToken() async {
    if (!AppConfig.canSelfGenerateToken) return null;

    try {
      final response = await _client.post(
        _endpoint,
        headers: {
          'Content-Type': 'application/json; charset=UTF-8',
          'Dev-Id': AppConfig.terraDevId,
          'x-api-key': AppConfig.terraApiKey,
        },
      );

      if (response.statusCode == 200) {
        final body = jsonDecode(response.body) as Map<String, dynamic>;
        final token = body['token'] as String?;
        if (token != null && token.isNotEmpty) return token;
      }
      debugPrint('TerraAuthService: token request failed '
          '(${response.statusCode}) ${response.body}');
    } catch (e) {
      debugPrint('TerraAuthService: token request errored — $e');
    }
    return null;
  }
}
