/// A parsed "connect" instruction — either handed to the app by the website via
/// deep link, or assembled locally once a pairing code has been redeemed.
///
/// Expected link shapes:
/// * `personallyhealth://connect?ref=<USER_ID>` — the website's hand-off. The
///   reference id alone is enough; the app resolves a Terra auth token itself.
/// * `personallyhealth://connect?token=<AUTH_TOKEN>&reference_id=<REF>&redirect=<RETURN_URL>`
///   — a backend-minted token, which takes priority when present.
class ConnectRequest {
  const ConnectRequest({
    this.token,
    this.referenceId,
    this.redirectUrl,
  });

  /// Single-use Terra auth token generated by the Personally backend
  /// (`POST /v2/auth/generateAuthToken`). Optional — when the link carries only
  /// a reference id, the app resolves a token itself.
  final String? token;

  /// The member's Personally user id, used as Terra's `reference_id`. This is
  /// what links the wearable connection back to their Personally account.
  final String? referenceId;

  /// Where to send the member once the sync completes (back to the website).
  final String? redirectUrl;

  /// A copy with individual fields replaced — used when pairing fills in the
  /// reference id on a request that already exists.
  ConnectRequest copyWith({
    String? token,
    String? referenceId,
    String? redirectUrl,
  }) =>
      ConnectRequest(
        token: token ?? this.token,
        referenceId: referenceId ?? this.referenceId,
        redirectUrl: redirectUrl ?? this.redirectUrl,
      );

  /// Builds a request from an incoming deep-link [uri], or returns `null` if it
  /// carries neither a reference id nor a token.
  static ConnectRequest? fromUri(Uri uri) {
    // Accept both `scheme://connect?...` and `https://.../connect?...` forms.
    final isConnect = uri.host == 'connect' ||
        uri.pathSegments.contains('connect') ||
        uri.queryParameters.containsKey('token') ||
        uri.queryParameters.containsKey('ref');
    if (!isConnect) return null;

    final token = _clean(uri.queryParameters['token']);
    final referenceId = _clean(uri.queryParameters['ref']) ??
        _clean(uri.queryParameters['reference_id']);

    // Nothing usable — not a connect link we can act on.
    if (token == null && referenceId == null) return null;

    return ConnectRequest(
      token: token,
      referenceId: referenceId,
      redirectUrl: _clean(uri.queryParameters['redirect']),
    );
  }

  static String? _clean(String? value) {
    final v = value?.trim();
    return (v == null || v.isEmpty) ? null : v;
  }

  @override
  String toString() {
    final value = token;
    final masked = value == null
        ? '<none>'
        : '${value.substring(0, value.length.clamp(0, 6))}…';
    return 'ConnectRequest(token: $masked, referenceId: $referenceId, '
        'redirectUrl: $redirectUrl)';
  }
}
