/// A parsed "connect" instruction handed to the app by the website via deep link.
///
/// Expected link shape:
/// `personallyhealth://connect?token=<AUTH_TOKEN>&reference_id=<REF>&redirect=<RETURN_URL>`
class ConnectRequest {
  const ConnectRequest({
    required this.token,
    this.referenceId,
    this.redirectUrl,
  });

  /// Single-use Terra auth token generated by the Personally backend
  /// (`POST /v2/auth/generateAuthToken`). Required to open a connection.
  final String token;

  /// Terra reference id for this member. Optional — falls back to config.
  final String? referenceId;

  /// Where to send the member once the sync completes (back to the website).
  final String? redirectUrl;

  /// Builds a request from an incoming deep-link [uri], or returns `null` if it
  /// is not a valid connect link (no usable token).
  static ConnectRequest? fromUri(Uri uri) {
    // Accept both `scheme://connect?...` and `https://.../connect?...` forms.
    final isConnect = uri.host == 'connect' ||
        uri.pathSegments.contains('connect') ||
        uri.queryParameters.containsKey('token');
    if (!isConnect) return null;

    final token = uri.queryParameters['token']?.trim();
    if (token == null || token.isEmpty) return null;

    return ConnectRequest(
      token: token,
      referenceId: _clean(uri.queryParameters['reference_id']),
      redirectUrl: _clean(uri.queryParameters['redirect']),
    );
  }

  static String? _clean(String? value) {
    final v = value?.trim();
    return (v == null || v.isEmpty) ? null : v;
  }

  @override
  String toString() =>
      'ConnectRequest(token: ${token.substring(0, token.length.clamp(0, 6))}…, '
      'referenceId: $referenceId, redirectUrl: $redirectUrl)';
}
